---
- hosts: all
  become: yes
  gather_facts: yes

  roles:
    - olidrouin.nfs
    - olidrouin.packer_debian

  tasks:
    - name: Install some helpful utilities.
      apt:
        name:
          - git
          - wget
          - curl
          - vim
        state: latest
